
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildDir: '/build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    npm install
    npm run build
  displayName: 'npm install and build'

- bash: |
    ls - l
    make build
  displayName: show all files and folders

- bash: |
    ls - l
  displayName: show all files and folders

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'